version: "2"
linters:
  default: all
  disable:
    - depguard
    - godox
    - gomoddirectives
    - protogetter
    - tagliatelle
    - varnamelen
  settings:
    ireturn:
      allow:
        - error
        - stdlib
        - generic
    wrapcheck:
      ignore-sigs:
        - errors.New(
        - errorx.Decorate(
        - status.Error(
        - status.Errorf(
        - fmt.Errorf(
        - (*google.golang.org/grpc/internal/status.Status).Err(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
